aboutme/urls.py
from django.urls import path

from aboutme import views

app_name = "aboutme"

urlpatterns = [
    path('', views.profile, name='profile')
]

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    # 포스트 목록
    path('', views.index, name='index'),
    # 포스트 상세 페이지
    path('<int:pk>/', views.detail, name='detail'),
    # 포스트 등록
    path('post/create', views.post_create, name='post_create'),
    # 포스트 삭제
    path('post/delete/<int:pk>/', views.post_delete, name='post_delete'),
    # 포스트 수정
    path('post/modify/<int:pk>/', views.post_modify, name='post_modify'),
    # 댓글 등록
    path('comment/create/<int:pk>/', views.comment_create, name='comment_create'),
    # 댓글 삭제
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    # 댓글 수정
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),


]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from common import views

app_name = 'common'

urlpatterns = [
    # 로그인
    path('login/', auth_views.LoginView.as_view(
        template_name = 'common/login.html'), name='login'),
    # 로그아웃
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원 가입
    path('signup/', views.signup, name='signup')
]

myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),
    path('aboutme/', include('aboutme.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutme/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.contrib.auth.models import User
from django.db import models

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)   # 글쓴이
    title = models.CharField(max_length=100)                     # 포스트 제목
    content = models.TextField()                                 # 포스트 내용
    pub_date = models.DateTimeField()                            # 작성일
    modify_date = models.DateTimeField(null=True, blank=True)    # 수정일
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/', # 사진
                              null=True, blank=True)
    # author는 추후 작성

    def __str__(self):
        return self.title

# 댓글 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 댓글 글쓴이
    content = models.TextField()                               # 댓글 내용
    pub_date = models.DateTimeField()                          # 댓글 작성일
    modify_date = models.DateTimeField(null=True, blank=True)  # 댓글 수정일
    post = models.ForeignKey(Post, null=True, blank=True,      # 포스트(외래키)
                             on_delete=models.CASCADE)

common/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Post, Comment

# 포스트 폼
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'photo']
        labels = {
            'title': '제목',
            'content': '내용',
            'photo': '사진'
        }

# 댓글 폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content': '댓글 내용'}

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')

aboutme/views.py
from django.shortcuts import render

def profile(request):
    return render(request, 'aboutme/profile.html')

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from blog.forms import PostForm, CommentForm
from blog.models import Post, Comment

def index(request):
    #블로그 홈
    post_list = Post.objects.order_by('-pub_date')
    context = {'post_list':post_list}
    return render(request, 'blog/post_list.html', context)

def detail(request, pk):
    # 블로그 상세 페이지
    #post = Post.objects.get(id=pk)
    post = get_object_or_404(Post, pk=pk)  #url경로 오류 처리
    context = {'post':post}
    return render(request, 'blog/post_detail.html', context)

@login_required(login_url='common:login')
def post_create(request):
    # 글 쓰기
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user   #작성자 - 세션 발급
            form.pub_date = timezone.now()
            form.modify_date = timezone.now()
            form.save()
            return redirect('blog:index')
    else:
        form = PostForm()
    context = {'form':form}
    return render(request, 'blog/post_form.html', context)

# 포스트 삭제
@login_required(login_url='common:login')
def post_delete(request, pk):
    # 포스트 삭제
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:index')

@login_required(login_url='common:login')
def post_modify(request, pk):
    # 포스트 수정
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modify_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.id)
    else:
        form = PostForm(instance=post)
    context = {'form':form}
    return render(request, 'blog/post_form.html', context)

@login_required(login_url='common:login')
def comment_create(request, pk):
    # 댓글 등록
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user  #세션
            comment.pub_date = timezone.now()
            comment.post = post   # 포스트(외래키)
            comment.save()
            return redirect('blog:detail', pk=post.id)
    else:
        form = CommentForm()
    context = {'form':form}
    return render(request, 'blog/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    # 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('blog:detail', pk=comment.post.id)

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    # 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('blog:detail', pk=comment.post.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form':form}
    return render(request, 'blog/comment_form.html', context)

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()  #가입 완료
            # 가입시 자동 로그인
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)
            login(request, user)  # 로그인
            return redirect('blog:index')
    else:
        form = UserForm()
    context = {'form':form}
    return render(request, 'common/signup.html', context)

templates/aboutme/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="profile">
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
        <h3>긍정 에너지 <em>Software Engineer</em> 김기용입니다.</h3>
            <div class="card my-4" style="max-width: 600px;">
              <div class="row g-0">
                <div class="col-md-4">
                  <img src="{% static 'aboutme/images/giyong0.jpg' %}"
                       class="img-fluid rounded-start" alt="증명사진">
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title">profile</h5>
                    <p class="card-text">
                        - 사는 곳 : 서울시 은평구 불광동<br>
                        - 하는 일 : 파이썬, 자바 기반 웹 프로그래밍 강의
                    </p>
                    <p class="card-text">
                        <small>깃허브 | https://github.com/sugu2100</small><br>
                        <small>Blog | https://blog.naver.com/sugu2000kr</small>
                    </p>
                  </div>
                </div>
              </div>
            </div>
        <h4 class="mt-4">Career</h4>
        <hr>
        <ul>
            <li>에듀윌 국비 교육원(부평센터) : 파이썬 기반 WEB 개발자 양성 강의</li>
            <li>메가패스 더조은 컴퓨터(노원캠퍼스) : 프로그래밍 입문 강의</li>
            <li>JMP 코리아(직업 전문 학교) : 자바 WEB 실무 일본 취업 강의</li>
            <li>전자 정부 프레임워크 실무 과정 수료</li>
            <li>예일 여고 아두이노 동아리 지도교사</li>
        </ul>
        <h4 class="mt-4">Skills</h4>
        <hr>
        <ul>
            <li>Backend | Python, Java</li>
            <li>Front | HTML, CSS, JavaScript</li>
            <li>FrameWork | Dajngo, Spring</li>
            <li>SQL | Sqlite3, Oracl</li>
            <li>IOT | 아두이노, 라즈베리파이</li>
        </ul>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>giyong's Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
{% include 'navbar.html' %}
<!-- 본문 영역-->
{% block content %}

{% endblock %}
<!-- 자바스크립트 영역 -->
<script src="{% static 'blog/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
{% block script %}

{% endblock %}

</body>
</html>

templates/blog/comment_form.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container my-3">
    <div class="row">
        <div class="col-lg-8">
            <form action="" method="post">
            <!-- 일반 필드와 이미지필드로 멀티파트로 구성됨-->
                {% csrf_token %}
    <!--                {{ form.as_p }}-->
                <div class="form-group">
                    <label for="content">댓글 내용</label>
                    <textarea name="content" id="content" rows="10"
                              class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">저장하기</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container my-3">
    <div class="row">
        <div class="col-8">
            <h3 class="my-3">{{ post.title }}</h3>
            <h6>
                {{ post.pub_date }}
                {% if post.modify_date %}
                   (수정:{{ post.modify_date }})
                {% endif %}
                {% if request.user == post.author %}
                <a href="{% url 'blog:post_modify' post.id %}">수정</a>
    <!--            <a onclick="return confirm('정말로 삭제하시겠습니까?')"-->
    <!--               href="{% url 'blog:post_delete' post.id %}">삭제</a>-->
                <a href="#" class="delete"
                   data-uri="{% url 'blog:post_delete' post.id %}">삭제</a>
                {% endif %}
            </h6>
            <hr>

            {% if post.photo %}
            <div class="card">
                <img src="{{ post.photo.url }}">
            </div>

            <div class="my-3" style="white-space:pre-line">{{ post.content }}</div>
            {% endif %}
            <div class="my-3">
                {% for comment in post.comment_set.all %}
                <div class="comment">
                    <span style="white-space:pre-line">
                        {{ comment.content }}
                    </span>
                    <span>
                        - {{ comment.author }}, {{ comment.pub_date }}
                          {% if comment.modify_date %}
                            (수정:{{ comment.modify_date }})
                          {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                        <a href="{% url 'blog:comment_modify' comment.id %}">수정</a>
                        <a href="#" class="delete"
                           data-uri="{% url 'blog:comment_delete' comment.id %}">삭제</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
                <hr>
            <div class="mt-3">
                <a href="{% url 'blog:comment_create' post.id %}">댓글 추가..</a>
            </div>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block script %}
<script>
    $(function(){
        //포스트, 댓글 삭제
        $(".delete").on('click', function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container my-3">
    <div class="row">
        <div class="col-lg-8">
            <h4 class="my-3">포스트 등록</h4>
            <form action="" method="post" enctype="multipart/form-data">
            <!-- 일반 필드와 이미지필드로 멀티파트로 구성됨-->
                {% csrf_token %}
        <!--                {{ form.as_p }}-->
                {% include 'form_errors.html' %}
                    <div class="form-group">
                        <label for="title">제목</label>
                        <input type="text" name="title" id="title" class="form-control"
                               value="{{ form.title.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <label for="content">내용</label>
                        <textarea name="content" id="content" rows="10"
                                  class="form-control">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="photo">사진</label>
                        <input type="file" name="photo" id="photo" class="form-control">
                    </div>
                <button type="submit" class="btn btn-primary">저장하기</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container">
    <div class="row">
        <div class="col-lg-8">
        {% if post_list %}
            {% for post in post_list %}
                <h3 class="mt-4">
                    <a href="{% url 'blog:detail' post.id %}">
                    {{ post.title }}
                    </a>
                </h3>
                <p class="lead">
                    by {{ post.author }} <small>({{ post.pub_date }})</small>
                </p>
                <hr>

                {% if post.photo %}
                <div class="card">
                    <img src="{{ post.photo.url }}">
                </div>
                {% endif %}

                <p style="white-space:pre-line;">
                    {{ post.content }}
                </p>
                <hr>
            {% endfor %}
        {% else %}
            <p>포스트가 없습니다.</p>
        {% endif %}
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container my-3">
    <div class="row">
        <div class="col-lg-8">
            <h4  class="my-3">로그인</h4>
            <form action="" method="post">
                {% csrf_token %}
                {% include 'form_errors.html' %}
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" name="username" id="username" class="form-control"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password">비밀번호</label>
                    <input type="password" name="password" id="password" class="form-control"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-success">로그인</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<section>
<div class="container my-3">
    <div class="row">
        <div class="col-lg-8">
            <h4 class="my-3">회원 가입</h4>
            <form action="" method="post">
                {% csrf_token %}
                {% include 'form_errors.html' %}
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" name="username" id="username" class="form-control"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password1">비밀번호</label>
                    <input type="password" name="password1" id="password1" class="form-control"
                           value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="password2">비밀번호 확인</label>
                    <input type="password" name="password2" id="password2" class="form-control"
                           value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="form-group">
                    <label for="email">이메일</label>
                    <input type="email" name="email" id="email" class="form-control"
                           value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="btn btn-success">가입</button>
                <button type="reset" class="btn btn-secondary">취소</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger">
    {% for field in form %}
        {% for error in field.errors %}
            <p><b>{{ field.label }}</b></p>
            <p>{{ error }}</p>
        {% endfor %}
    {% endfor %}
    </div>
{% endif %}

templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light container">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Blog</a>
    <!--햄버거 메뉴 -->
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- 메뉴 -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">({{ user.username }})로그아웃</a>
          {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_create' %}">글쓰기</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'aboutme:profile' %}">About Me</a>
        </li>
      </ul>
    </div>
  </div>
</nav>